module:
  mounts:
    - source: archetypes
      target: archetypes
    - source: assets
      target: assets
    - source: data
      target: data
    - source: i18n
      target: i18n
    - source: layouts
      target: layouts
    - source: static
      target: static
  imports:
    - path: github.com/jgthms/bulma
      version: 1.0.4
      mounts:
      - source: .
        target: assets/scss
      - source: sass
        target: assets/scss/bulma/sass