[params]
  # Website logo file paths
  logo                    = "images/logo.png"
  logoTouch               = "images/logoTouch.png"
  # Image file path displayed during a 404 error
  image404                = "images/404.gif"
  # Favicon website file path
  favicon                 = "images/favicon.png"
  # Default layout used for the homepage
  homeLayout              = "onboarding"
  # Site content order (https://gohugo.io/templates/lists/#order-content)
  siteContentOrder        = "weight"
  # Activate/Deactivate the table of contents globally (sitewide)
  toc                     = true
  # Activate a global banner on all website pages
  globalBanner            = true
  # Curent version of the website
  currentVersion          = "latest"
  # Url of the latest version of the website
  latestVersionUrl        = "https://jgazeau.github.io/shadocs/"
  # Enforce Link resolution using relref function (https://gohugo.io/content-management/cross-references/)
  enforceRefrelLinks      = true
  # Disable "Print" button in navbar
  navbarPrintEntry        = false
  # Disable "QR code" button in navbar
  navbarQRCodeEntry       = false
  # Disable "Shortcuts" button in navbar
  navbarSchortcutsEntry   = false
  # Disable "About" button in navbar
  navbarInfo              = false
  # Keyboard shortcuts list
  # For each shortcut following keys must be sets:
  # - keys     = [Keyboard shortcuts table](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values)
  # - function = "Javascript function name to call by the shortcut"
  [params.navbar.shortcuts]
    # Example shortcut definition
    [params.navbar.shortcuts.example]
      keys     = ["Shift","1"]
      function = "scExample"
  # Taxonomies list
  # For each taxonomy following keys can be sets:
  # - icon = "Fontawesome classes associated to the taxonomy"
  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
  #
  # Assets list (https://gohugo.io/hugo-pipes/resource-from-template/) to include
  # Managed assets:
  # - css                   = [List of CSS files]
  # - js                    = [List of javascript files]
  # - jsModules             = [List of javascript modules]
  # - fencedcodes.css       = [List of CSS files to includes when the associated language of fenced code exist in the page content]
  # - fencedcodes.js        = [List of javascript files to includes when the associated language of fenced code exist in the page content]
  # - fencedcodes.jsModules = [List of javascript module files to includes when the associated language of fenced code exist in the page content]
  # - shortcodes.css        = [List of CSS files to includes when the associated shortcode exist in the page content]
  # - shortcodes.js         = [List of javascript files to includes when the associated shortcode exist in the page content]
  # - shortcodes.jsModules  = [List of javascript module files to includes when the associated shortcode exist in the page content]
  #
  [params.includes]
    css = [
      "css/file1.css",
      "css/fileX.css"
    ]
    js = [
      "js/file1.js",
      "js/fileX.js"
    ]
    jsModules = [
      "js/modules/file1.js",
      "js/modules/fileX.js"
    ]
  [params.includes.fencedcodes.css]
    fencedcode1 = [
        "css/fencedcodes/fencedcode1.css"
      ]
    fencedcodeX = [
        "css/fencedcodes/fencedcodeX.css"
      ]
  [params.includes.fencedcodes.js]
    fencedcode1 = [
        "js/fencedcodes/fencedcode1.js"
      ]
    fencedcodeX = [
        "js/fencedcodes/fencedcodeX.js"
      ]
  [params.includes.fencedcodes.jsModules]
    fencedcode1 = [
        "js/fencedcodes/modules/fencedcode1.js"
      ]
    fencedcodeX = [
        "js/fencedcodes/modules/fencedcodeX.js"
      ]
  [params.includes.shortcodes.css]
    shortcode1 = [
        "css/shortcodes/shortcode1.css"
      ]
    shortcodeX = [
        "css/shortcodes/shortcodeX.css"
      ]
  [params.includes.shortcodes.js]
    shortcode1 = [
        "js/shortcodes/shortcode1.js"
      ]
    shortcodeX = [
        "js/shortcodes/shortcodeX.js"
      ]
  [params.includes.shortcodes.jsModules]
    shortcode1 = [
        "js/shortcodes/modules/shortcode1.js"
      ]
    shortcodeX = [
        "js/shortcodes/modules/shortcodeX.js"
      ]